<?php

namespace ContainerJpxSNsZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QoDeLCPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qoDeLCP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qoDeLCP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', '.errored..service_locator.qoDeLCP.App\\Entity\\Defis', NULL, 'Cannot autowire service ".service_locator.qoDeLCP": it references class "App\\Entity\\Defis" but no such service exists.'],
        ], [
            'data' => 'App\\Entity\\Defis',
        ]);
    }
}
