<?php

<<<<<<< HEAD:var/cache/dev/ContainerJpxSNsZ/getResponseService.php
namespace ContainerJpxSNsZ;
=======
namespace ContainerZxSUX7U;
>>>>>>> 760c35a48d05eb44fce49ee1c396f1bb53e1480e:var/cache/dev/ContainerZxSUX7U/getResponseService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.beq5mCo.Symfony\Component\HttpFoundation\Response' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.beq5mCo": it references class "Symfony\\Component\\HttpFoundation\\Response" but no such service exists.');
    }
}
