<?php

<<<<<<< HEAD:var/cache/dev/ContainerDHwdnTr/getResponseService.php
namespace ContainerDHwdnTr;
=======
namespace ContainerToHWxcP;
>>>>>>> 224edc0a883c202bdaa54fa3d75deca233237923:var/cache/dev/ContainerToHWxcP/getResponseService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.beq5mCo.Symfony\Component\HttpFoundation\Response' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.beq5mCo": it references class "Symfony\\Component\\HttpFoundation\\Response" but no such service exists.');
    }
}
