<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHFgLJyb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHFgLJyb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHFgLJyb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHFgLJyb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHFgLJyb\App_KernelDevDebugContainer([
    'container.build_hash' => 'HFgLJyb',
    'container.build_id' => '9ee9b590',
    'container.build_time' => 1593616882,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHFgLJyb');
