<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerToHWxcP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerToHWxcP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerToHWxcP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerToHWxcP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerToHWxcP\App_KernelDevDebugContainer([
    'container.build_hash' => 'ToHWxcP',
    'container.build_id' => '6553a116',
    'container.build_time' => 1594048576,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerToHWxcP');
