<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJR3bpvj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJR3bpvj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJR3bpvj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJR3bpvj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJR3bpvj\App_KernelDevDebugContainer([
    'container.build_hash' => 'JR3bpvj',
    'container.build_id' => '3e1326d6',
    'container.build_time' => 1593788196,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJR3bpvj');
